name: "Publish"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        # Install Python dependencies (which includes pytest) so
        # that the tests can be run
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install poetry
        poetry install

    - name: Build the project
      run: |
        poetry build

    - name: Install Twine
      run: |
        python -m pip install --user twine

    - name: Publish the project to PyPi
      env:
        TWINE_REPOSITORY: pypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
