name: "PyTest"

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # Install Python dependencies (which includes pytest) so
        # that the tests can be run
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install poetry
        poetry install

    - name: Run unit tests
      run: |
        "$(poetry env info --path)"/bin/pytest
